### ISSUE TITLE
data abort

### ISSUE THREAD

**Issue by pcs3rd** [Pirater12/Multidownload#10]
o3ds+a9lh+luma3ds
crashes after typing in a link or trying to updare the utility
here is the dump file https://drive.google.com/open?id=0B6rsrExPQ0PXLVBab2t2QTJ5VnM

**Comment by Pirater12** [comment]
Multidownload has become unstable due to extra long scripts.Don't use for now.I am currently in the process of rewriting multidownload+I'm having my exams ,so give like 20 days after which I'll upload the stable code

**Comment by pcs3rd** [comment]
@Pirater12 fair warning, you app has been marked working on some gbatemp threads, what is the last version to work, also a nice feature to add in is history so that if a download fails, you can just go back and retry
