### ISSUE TITLE
Am I doing something wrong? It’s not working

### ISSUE THREAD

**Issue by kokichioumalovesme** [Pirater12/Multidownload#13]
Hi! I’m using a New 3DS with everything up to date as of the time I’m posting this (11.9.0.42U firmware, 3.6 NTR, Luna 9.1, etc). I also have an old 3ds with the same things, if that matters.

Anyways, for my issue. I use CTRX to manage most of my files and create my folders, however I’m trying to use this to download some NTR plugins for my games. I know where to put them, but the problem is, they’re not even downloading at all! It always says failed. I’ve tried downloading with the URLs on this site (on MegaNTR depository), downloading them from all the cloud services on the first page of google, nothing works. Is there a specific requirement I’m missing? Or is it completely broken?

By the way I have only tried downloading .plg files, so idk if it works on other formats

**Comment by hax0kartik** [comment]
It's been a long time since I have maintained this It's most likely broken :(

**Comment by kokichioumalovesme** [comment]
Ah, alright then. I guess I’ll just have to pursue my plan b. Thank you anyways. Closing now
