### ISSUE TITLE
Not connected to Internet?

### ISSUE THREAD

**Issue by ghost** [Pirater12/Multidownload#14]
Hi there, I know this homebrew app is pretty old.
But still, I am trying to connect to someone, because i have an issue.
Everytime, I download a file (from a direct link of course), i get an error that i'm not connected to the internet. I know i am connected to my internet and that it works 100% 
Every time I download a file it gives me following output:

Downloading: (website)
Error 0xd8a0a03c
Wrong protocol/Internet not connected (website)
returning in 5 seconds...
(The Format is zip)

But, i tried it with google's website Icon:
Downloading: https://google.com/favicon.ico
Status: Success
(The Format is ico)

But why did it work?

Any help is welcome!

**Comment by hax0kartik** [comment]
What's the link you are trying to download?

**Comment by ghost** [comment]
The link is: https://static.wiidatabase.de/USB-Loader-GX.zip
Don't judge, i lost my SD card Reader

**Comment by hax0kartik** [comment]
Well I advice you to not use md anymore, it's just broken at the point and
I don't really have time to fix it. Sorry.

**Comment by ghost** [comment]
Well alright then, have a great christmas!
