### ISSUE TITLE
QR code scanner does not work

### ISSUE THREAD

**Issue by lmore377** [Pirater12/Multidownload#2]
I'm trying to scan a QR code but the camera doesn't activate. I attached what the bottom screen says.

![1491610982354-1685102230](https://cloud.githubusercontent.com/assets/24685455/24823746/46da2852-1bbf-11e7-871d-57366b5e8c13.jpg)

**Comment by lmore377** [comment]
Never mind. I forgot the smdh file. :P

**Comment by lmore377** [comment]
I downloaded the 3dsx and smdh file. Still doesn't work.

**Comment by hax0kartik** [comment]
Sorry to be late, you will need to to put tthe xml file which i just uploaded on the relase page  in the same location as the 3dsx .Now when you launch the 3dsx it will show a "Target title selector".Scroll using the dpad and select "Face raiders".

**Comment by lmore377** [comment]
It works! Only thing is that face raiders doesn't show up, but swapnote does and it works.
