### ISSUE TITLE
Looking for testers If interested please comment

### ISSUE THREAD

**Issue by Pirater12** [Pirater12/Multidownload#3]
I need some people to test out qr code feature(my 3ds cameras don"t work) which I will be adding if interested please coment

**Comment by deadair3210** [comment]
I would be willing to help if needed, I have a o3DS and an o3DS XL, both on a9lh Luma3DS 11.0

**Comment by Yoshistar95** [comment]
I'd like to help too, mine's an o3DS XL with rxTools emuNAND on 11.0 (sysNAND 9.2).

**Comment by gnmmarechal** [comment]
I'm willing to help. I own a 2DS on 11.0 with Corbenik CFW 0.2.0.

**Comment by SirBeethoven** [comment]
I'd love to help!!

**Comment by pcs3rd** [comment]
I would like to help. ( o3ds+luma3ds 6.6+a9lh)
and I can give dumps of errors
