### ISSUE TITLE
Download Crashes at 30+MB

### ISSUE THREAD

**Issue by McJordan447** [Pirater12/Multidownload#8]
Yesterday I was trying to download a nds file directly to my 3DS (80MB) and after trying a couple times i noticed it always crashed around 30MB. Is this a "me" problem or is it a software limitation?

**Comment by hax0kartik** [comment]
This is a known issue, I will soon push some commits which will fix this issue

**Comment by McJordan447** [comment]
Thank you a lot!!! This will make my life a lot easier, saving me a good number of hours of work! Please notify me in this issue when it's out if you could be so kind! ( ^o^)/

**Comment by hax0kartik** [comment]
@McJordan447 Would you have the time to try this ?
[Multidownload++.zip](https://github.com/Pirater12/Multidownload/files/1150115/Multidownload.zip)

**Comment by McJordan447** [comment]
I'm on it

**Comment by McJordan447** [comment]
File Name:
Pokemon Conquest [U].zip

File Link:
http://www.mediafire.com/?si2bxtveile78la

File Size:
70.00 MBs

Bug: When the percentajes hit X9% they start showing letters instead of a second digit in the sequence of the following example:

49% > 4a% > 4b% > 4c% > 4d% > 4e% > 4f% > 50%

This causes a delay in the percentaje:

Download finished at 64%

- 10MBs ~ Passed
- 20MBs ~ Passed
- 30MBs ~ Passed
- 40MBs ~ Passed
- 50MBs ~ Passed
- 60MBs ~ Passed
- 70MBs ~ Passed

DOWNLOAD WAS SUCESSFUL

Note: All procedures were sucessful, however MultiDownloads++ froze after it was done downloading and extracting the files.

I hope this information serves to improve your homebrew even further! ( ^v^)/

**Comment by McJordan447** [comment]
PD: Correction - Multidownload froze while it was un-zipping the file meaning the file wasn't unzipped in the process.
